name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  html-validate:
    name: Validate HTML & links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/stage-site

      # Validate HTML & CSS + check images/links (Nu HTML Validator + HTMLProofer)
      - uses: anishathalye/proof-html@v2 
        with:
          directory: ./site
          enforce_https: true
          check_html: true
          check_favicon: true
          check_opengraph: true
          check_css: true

  linkcheck:
    name: Broken-link scan (lychee)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/stage-site

      - uses: lycheeverse/lychee-action@v2   # Fast link checker
        with:
          args: >-
            --verbose
            --no-progress
            --exclude "localhost|127\.0\.0\.1"
            ./site
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md

  secrets:
    name: Secrets scan (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Ensure we have the full git history for gitleaks to scan
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --verbose --redact
        env:
          GITLEAKS_ENABLE_COMMENTS: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  accessibility:
    name: Accessibility (pa11y-ci)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/stage-site

      # Serve the static files
      - run: npx http-server -p 8080 site -s & npx wait-on http://127.0.0.1:8080/index.html
      - run: npx pa11y-ci

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/stage-site
      - run: npm i -D @lhci/cli
      - run: npx http-server -p 39107 site -s & npx wait-on http://127.0.0.1:39107/index.html
      - run: npx lhci autorun --collect.url=http://127.0.0.1:39107/index.html --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN || ''}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

