name: Deploy site (live)
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Build Tailwind CSS
        run: |
          npm i -D tailwindcss@3.4.13
          npx tailwindcss -i assets/input.css -o assets/site.css --minify

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean-exclude: pr-preview/
          force: false

