name: Deploy PR preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency: preview-${{ github.event.pull_request.number || github.ref }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Build Tailwind CSS
        run: |
          npm i -D tailwindcss@3.4.13
          npx tailwindcss -i assets/input.css -o assets/site.css --minify

      - name: Prepare preview bundle
        run: |
          rm -rf site
          mkdir -p site
          cp -a index.html site/
          cp -a insights site/ || true
          cp -a assets site/ || true
          cp -a favicon.ico site/ || true
          touch site/.nojekyll

      # Ensure gh-pages root has .nojekyll so GH Pages never runs Jekyll on previews
      - name: Ensure .nojekyll at gh-pages root
        if: ${{ github.event.action == 'opened' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: .
          clean: false
          # publish only the single file
          git-config-email: github-actions[bot]@users.noreply.github.com
          git-config-name: github-actions[bot]
        env:
          # create a temp .nojekyll file at workspace root just for this push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: touch .nojekyll

      - name: Deploy (create/update/remove) preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto

