name: Deploy PR preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy (create/update/remove) preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
          

