# .github/workflows/zap.yml
name: ZAP baseline (live)
on:
  workflow_run:
    workflows: ["Deploy site (live)"]
    types: [completed]

jobs:
  zap:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://chris-sorensen.github.io/consulting/'
          rules_file_name: '.zap/rules.tsv'
          # Avoid artifact API error:
          artifact_name: 'zap-scan-${{ github.run_id }}'
          # Keep a single rolling issue rather than creating many:
          issue_title: 'ZAP Scan Baseline Report'
          # Avoid AF writing zap.yaml in the mounted workspace
          cmd_options: >-
            --autooff
            -m 5
            -d


