# .github/workflows/zap.yml
name: ZAP baseline (live)
on:
  workflow_run:
    workflows: ["Deploy site (live)"]
    types: [completed]

jobs:
  zap:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: https://chris-sorensen.github.io/
          cmd_options: -a -m 5

